services:
  postgres-carsties:
    image: postgres:14-alpine
    container_name: auction_db
    environment:
      - POSTGRES_PASSWORD=Dev@Null
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo-carsties:
    image: mongo
    container_name: search_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo_pw
    ports:
      - 27018:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq-carsties:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitdata:/var/lib/rabbitmq
  auction-svc:
    image: evanshango/auction-svc:latest
    container_name: auction-svc
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMQ__Host=rabbitmq-carsties
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__DefaultConnection=Server=postgres-carsties;User Id=postgres;Password=Dev@Null;Database=auction_db
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - postgres-carsties
      - rabbitmq-carsties
  search-svc:
    image: evanshango/search-svc:latest
    container_name: search-svc
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq-carsties
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongo_pw@mongo-carsties
    ports:
      - 7002:80
    depends_on:
      - mongo-carsties
      - rabbitmq-carsties
  identity-svc:
    image: evanshango/identity-svc:latest
    container_name: identity-svc
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres-carsties;User Id=postgres;Password=Dev@Null;Database=identity_db
    ports:
      - 5001:80
    depends_on:
      - postgres-carsties
  bidding-svc:
    image: evanshango/bidding-svc:latest
    container_name: bidding-svc
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq-carsties
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongo_pw@mongo-carsties
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuctionAddress=http://auction-svc:7777
    ports:
      - 7003:80
    depends_on: 
      - mongo-carsties
      - rabbitmq-carsties
  notification-svc:
    image: evanshango/notification-svc:latest
    container_name: notification-svc
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq-carsties
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    ports:
      - 7004:80
    depends_on:
      - rabbitmq-carsties
  gateway-svc:
    image: evanshango/gateway-svc:latest
    container_name: gateway-svc
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
volumes:
  pgdata:
  mongodata:
  rabbitdata: