services:
  postgres-carsties:
    image: postgres:14-alpine
    container_name: auction_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=Dev@Null
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes: 
  pgdata: