networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16
services:
  postgres-carsties:
    image: postgres:14-alpine
    container_name: auction_db
    environment:
      - POSTGRES_PASSWORD=Dev@Null
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      custom:
  mongo-carsties:
    image: mongo
    container_name: search_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo_pw
    ports:
      - 27018:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
    networks:
      custom:
  rabbitmq-carsties:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    networks:
      custom:
  auction-svc:
    image: evanshango/auction-svc:latest
    container_name: auction-svc
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMQ__Host=rabbitmq-carsties
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__DefaultConnection=Server=postgres-carsties;User Id=postgres;Password=Dev@Null;Database=auction_db
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - postgres-carsties
      - rabbitmq-carsties
    networks:
      custom:
  search-svc:
    image: evanshango/search-svc:latest
    container_name: search-svc
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq-carsties
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongo_pw@mongo-carsties
    ports:
      - 7002:80
    depends_on:
      - mongo-carsties
      - rabbitmq-carsties
    networks:
      custom:
  identity-svc:
    image: evanshango/identity-svc:latest
    container_name: identity-svc
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres-carsties;User Id=postgres;Password=Dev@Null;Database=identity_db
      - ClientApp=http://app.carsties.local
      - VIRTUAL_HOST=id.carsties.local
    depends_on:
      - postgres-carsties
    networks:
      custom:
        ipv4_address: 10.5.0.200
  bidding-svc:
    image: evanshango/bidding-svc:latest
    container_name: bidding-svc
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq-carsties
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongo_pw@mongo-carsties
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuctionAddress=http://auction-svc:7777
    ports:
      - 7003:80
    depends_on:
      - mongo-carsties
      - rabbitmq-carsties
    networks:
      custom:
  notification-svc:
    image: evanshango/notification-svc:latest
    container_name: notification-svc
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq-carsties
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    ports:
      - 7004:80
    depends_on:
      - rabbitmq-carsties
    networks:
      custom:
  gateway-svc:
    image: evanshango/gateway-svc:latest
    container_name: gateway-svc
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=https://app.carsties.local
      - VIRTUAL_HOST=api.carsties.local
    networks:
      custom:
  web-app:
    image: evanshango/web-app:latest
    container_name: web-app
    build:
      context: .
      dockerfile: frontend/web-app/Dockerfile
      args:
        NEXTAUTH_SECRET: super_secret_key
        NEXTAUTH_URL: http://app.carsties.local
        NEXTAUTH_URL_INTERNAL: http://web-app:3000
        ID_SERVER_URL: http://id.carsties.local
        API_URL: http://gateway-svc/
        NEXT_PUBLIC_NOTIFICATION_URL: https://api.carsties.local/notifications
    environment:
      - HOSTNAME=localhost
      - VIRTUAL_HOST=app.carsties.local
      - VIRTUAL_PORT=3000
    volumes:
      - /var/lib/web/data
    extra_hosts:
      - id.carsties.local:10.5.0.200
    networks:
      custom:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: carsties-nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      custom:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs
volumes:
  pgdata:
  mongodata:
  rabbitdata: