services:
  postgres-carsties:
    image: postgres:14-alpine
    container_name: auction_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=Dev@Null
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo-carsties:
    image: mongo
    container_name: search_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo_pw
    ports:
      - 27018:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
volumes: 
  pgdata:
  mongodata: